#!/usr/bin/env bash

set -euo pipefail
source print-table

function red() {
    text="${1:- }"
    echo -e "\033[1;31m$text\033[0m"
}

function green() {
    text="${1:- }"
    echo -e "\033[1;32m$text\033[0m"
}

function yellow() {
    text="${1:- }"
    echo -e "\033[1;33m$text\033[0m"
}

function blue() {
    text="${1:- }"
    echo -e "\033[1;36m$text\033[0m"
}

function print_usage() {
    echo -e "\033[1;32mUsage:\033[0m $0 \033[1;33m <GCP Folder Id> <GKE Minimum Version(optional)> \033[0m"
    echo -e "\033[1;32mExample:\033[0m $0 \033[1;33m 907623304376 1.24 \033[0m"

}
# optional argument handling


if [[ -z "${1:-}" || "${1:- }" == "-h" || "${1:- }" == "--help" || "${1:- }" == "-help" ]]; then
    print_usage
    exit 0
fi

DEFAULT_GKE_MINIMUM_VERSION="1.21"
GCP_FOLDER_ID="${1:-}"
GKE_MINIMUM_VERSION="${2:-$DEFAULT_GKE_MINIMUM_VERSION}"

GCP_FOLDER_NAME="$(gcloud resource-manager folders describe "${GCP_FOLDER_ID}" --format 'csv[no-heading](displayName)')"

green "Getting all the clusters under folder => ${GCP_FOLDER_NAME}"

GKE_CLUSTERS=($(gcloud beta asset list --folder="${GCP_FOLDER_ID}" --format="csv[no-heading](name)" --asset-types='container.googleapis.com/Cluster'))

{
    echo -e 'GCP Project ID\tGKE Cluster Name\tMaster Version\tNode Version\n';
    for GKE_CLUSTER in "${GKE_CLUSTERS[@]}"; do
        GKE_CLUSTER="${GKE_CLUSTER##//container.googleapis.com/projects/}"

        GCP_PROJECT_ID="$(echo "${GKE_CLUSTER}" | cut  -d '/' -f 1)"
        GCP_LOCATION="$(echo "${GKE_CLUSTER}" | cut  -d '/' -f 2)"

        GKE_LOCATION="$(echo "${GKE_CLUSTER}" | cut  -d '/' -f 3)"

        GKE_CLUSTER_NAME="$(echo "${GKE_CLUSTER}" | cut  -d '/' -f 5)"

        if [[ ${GCP_LOCATION} == "zones" ]]; then
            LOCATION="--zone ${GKE_LOCATION}"
        else
            LOCATION="--region ${GKE_LOCATION}"
        fi

        GKE_CLUSTER_DETAILS="$(gcloud container clusters describe "${GKE_CLUSTER_NAME}" ${LOCATION} --project="${GCP_PROJECT_ID}" --format 'csv[no-heading](currentMasterVersion,currentNodeVersion)')"

        GKE_CLUSTER_MASTER_VERSION="$(echo "${GKE_CLUSTER_DETAILS}" | cut  -d ',' -f 1)"
        GKE_CLUSTER_NODE_VERSION="$(echo "${GKE_CLUSTER_DETAILS}" | cut  -d ',' -f 2)"

        GKE_CLUSTER_NODE_MAJOR_VERSION="$(echo "${GKE_CLUSTER_NODE_VERSION##-}" | cut  -d '.' -f 2)"

        if (( "${GKE_CLUSTER_NODE_MAJOR_VERSION}" < "${GKE_MINIMUM_VERSION##*.}" )); then
            printf '%s\t%s\t%s\t%s\n' "${GCP_PROJECT_ID}" "${GKE_CLUSTER}" "${GKE_CLUSTER_MASTER_VERSION}" "${GKE_CLUSTER_NODE_VERSION}";
        fi

    done

} | prettytable 4 green

